tasks:
  - init: |
      sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)"
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      eval $(gp env -e PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH)
    command: |
      solana-keygen new --no-bip39-passphrase -o keypair.json
      solana config set --keypair keypair.json
      solana config set --url localhost